export const textures = {
  grassTop: new URL("./minecraft-textures/block/grass_block_top.png", import.meta.url).href,
  grassSide: new URL("./minecraft-textures/block/grass_block_side.png", import.meta.url).href,
  dirt: new URL("./minecraft-textures/block/dirt.png", import.meta.url).href,
  oakPlanks: new URL("./minecraft-textures/block/oak_planks.png", import.meta.url).href,
  sprucePlanks: new URL("./minecraft-textures/block/spruce_planks.png", import.meta.url).href,
  stone: new URL("./minecraft-textures/block/stone.png", import.meta.url).href,
  cobblestone: new URL("./minecraft-textures/block/cobblestone.png", import.meta.url).href,
  deepslate: new URL("./minecraft-textures/block/deepslate.png", import.meta.url).href,
  obsidian: new URL("./minecraft-textures/block/obsidian.png", import.meta.url).href,
  diamond: new URL("./minecraft-textures/block/diamond_block.png", import.meta.url).href,
  emerald: new URL("./minecraft-textures/block/emerald_block.png", import.meta.url).href,
  redstone: new URL("./minecraft-textures/block/redstone_block.png", import.meta.url).href,
  bookshelf: new URL("./minecraft-textures/block/bookshelf.png", import.meta.url).href,
  craftingTop: new URL("./minecraft-textures/block/crafting_table_top.png", import.meta.url).href,
  craftingSide: new URL("./minecraft-textures/block/crafting_table_side.png", import.meta.url).href,
  craftingFront: new URL("./minecraft-textures/block/crafting_table_front.png", import.meta.url).href,
  enchantingTop: new URL("./minecraft-textures/block/enchanting_table_top.png", import.meta.url).href,
  enchantingSide: new URL("./minecraft-textures/block/enchanting_table_side.png", import.meta.url).href,
  enchantingBottom: new URL("./minecraft-textures/block/enchanting_table_bottom.png", import.meta.url).href,
  furnaceSide: new URL("./minecraft-textures/block/furnace_side.png", import.meta.url).href,
  furnaceFront: new URL("./minecraft-textures/block/furnace_front_on.png", import.meta.url).href,
  glass: new URL("./minecraft-textures/block/glass.png", import.meta.url).href,
  mossyStone: new URL("./minecraft-textures/block/mossy_stone_bricks.png", import.meta.url).href,
  amethyst: new URL("./minecraft-textures/block/amethyst_block.png", import.meta.url).href,
  lectern: new URL("./minecraft-textures/block/lectern_front.png", import.meta.url).href,
  rail: new URL("./minecraft-textures/block/rail.png", import.meta.url).href,
  poweredRail: new URL("./minecraft-textures/block/powered_rail_on.png", import.meta.url).href,
  portal: new URL("./minecraft-textures/block/nether_portal.png", import.meta.url).href,
  torch: new URL("./minecraft-textures/block/torch.png", import.meta.url).href,
};

export const items = {
  book: new URL("./minecraft-textures/item/book.png", import.meta.url).href,
  writtenBook: new URL("./minecraft-textures/item/written_book.png", import.meta.url).href,
  compass: new URL("./minecraft-textures/item/compass_00.png", import.meta.url).href,
  map: new URL("./minecraft-textures/item/map.png", import.meta.url).href,
  itemFrame: new URL("./minecraft-textures/item/item_frame.png", import.meta.url).href,
  painting: new URL("./minecraft-textures/item/painting.png", import.meta.url).href,
  diamondSword: new URL("./minecraft-textures/item/diamond_sword.png", import.meta.url).href,
  diamondPickaxe: new URL("./minecraft-textures/item/diamond_pickaxe.png", import.meta.url).href,
  ironSword: new URL("./minecraft-textures/item/iron_sword.png", import.meta.url).href,
  potion: new URL("./minecraft-textures/item/potion.png", import.meta.url).href,
  glowstoneDust: new URL("./minecraft-textures/item/glowstone_dust.png", import.meta.url).href,
  redstone: new URL("./minecraft-textures/item/redstone.png", import.meta.url).href,
  emerald: new URL("./minecraft-textures/item/emerald.png", import.meta.url).href,
  enderPearl: new URL("./minecraft-textures/item/ender_pearl.png", import.meta.url).href,
  minecart: new URL("./minecraft-textures/item/minecart.png", import.meta.url).href,
  chestMinecart: new URL("./minecraft-textures/item/chest_minecart.png", import.meta.url).href,
  feather: new URL("./minecraft-textures/item/feather.png", import.meta.url).href,
  experienceBottle: new URL("./minecraft-textures/item/experience_bottle.png", import.meta.url).href,
  enchantedBook: new URL("./minecraft-textures/item/enchanted_book.png", import.meta.url).href,
  lantern: new URL("./minecraft-textures/item/lantern.png", import.meta.url).href,
  bell: new URL("./minecraft-textures/item/bell.png", import.meta.url).href,
  amethystShard: new URL("./minecraft-textures/item/amethyst_shard.png", import.meta.url).href,
};
